version: "3.9"
services: 
  urban-memory:
    image: node:${NODE_VERSION:-16}
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - type: bind 
        source: ./urban-memory
        target: /app
    working_dir: /app
    command: yarn serve
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  glowing-fiesta: 
    image: node:${NODE_VERSION:-16}
    ports:
      - "4200:4200"
    volumes:
      - type: bind 
        source: ./glowing-fiesta
        target: /app
    working_dir: /app
    command: yarn start
    depends_on:
      - redis 
      - urban-memory
    environment:
      - REACT_APP_PROXY_HOST=htttp://host.docker.internal:3000
  redis: 
    image: redis
    ports:
      - "6379:6379"
